// <auto-generated />
using System;
using ApiAlmoxarifao.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAlmoxarifao.Api.Migrations
{
    [DbContext(typeof(AlmoxarifadoContext))]
    [Migration("20240226125918_DepartamentoMigration")]
    partial class DepartamentoMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiAlmoxarifao.Api.Models.Categoria", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"), 1L, 1);

                    b.Property<string>("CatDescricao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cat_descricao");

                    b.HasKey("CatId")
                        .HasName("PK__categori__DD5DDDBDCE421EB6");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("ApiAlmoxarifao.Api.Models.Departamento", b =>
                {
                    b.Property<int>("DepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dep_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepId"), 1L, 1);

                    b.Property<string>("DepDescricao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dep_descricao");

                    b.Property<bool?>("DepSituacao")
                        .HasColumnType("bit")
                        .HasColumnName("dep_situacao");

                    b.HasKey("DepId")
                        .HasName("PK__departam__BB4BD8F8CB71FE79");

                    b.ToTable("departamento");
                });

            modelBuilder.Entity("ApiAlmoxarifao.Api.Models.Produto", b =>
                {
                    b.Property<int>("ProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pro_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProId"), 1L, 1);

                    b.Property<int?>("CatId")
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    b.Property<int?>("ProEstoque")
                        .HasColumnType("int")
                        .HasColumnName("pro_estoque");

                    b.Property<string>("ProImg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("pro_img");

                    b.Property<string>("ProNome")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pro_nome");

                    b.HasKey("ProId")
                        .HasName("PK__produtos__335E4CA6D5258034");

                    b.HasIndex("CatId");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("ApiAlmoxarifao.Api.Models.Produto", b =>
                {
                    b.HasOne("ApiAlmoxarifao.Api.Models.Categoria", "Cat")
                        .WithMany("Produtos")
                        .HasForeignKey("CatId")
                        .HasConstraintName("FK__produtos__cat_id__3A81B327");

                    b.Navigation("Cat");
                });

            modelBuilder.Entity("ApiAlmoxarifao.Api.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
